name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3  # `javac` is required by tests
        with:
          distribution: "adopt"
          java-version: "11"
      - uses: ts-graphviz/setup-graphviz@v1  # `dot` is required by tests
      - name: Test
        run: cargo test --verbose
